### ISSUE TITLE
crashing when loading together with Lycanites Mobs

### ISSUE THREAD

**Issue by HaaDT** [yeelp/Distinct-Damage-Descriptions#69] opened 2021-10-01 13:04 UTC
the mod has a bug that when it is loaded together with the Lycanites Mobs, it loads open the forge everything right, but when it enters the world it crashes, loads everything right, but when it opens the world it crashes and closes the game

**Comment by yeelp** [comment] 2021-10-01 15:46
Do you have a crash log you can provide? I'm currently working on integrating Lycanites Mobs' equipment system with DDD, and have been able to load DDD with Lycanites Mobs perfectly fine in my dev environment.

**Comment by HaaDT** [comment] 2021-10-01 15:54
yes I can, but I was using VanillaFix that changes the log, does it have a problem?

**Comment by HaaDT** [comment] 2021-10-01 15:55
maybe it could also be some of the mods I was using together, but why did I take the Lycanites Mobs and it stopped crashing so I guessed it was him, but I'll send the log then

**Comment by yeelp** [comment] 2021-10-01 15:57
Having Vanilla Fix is alright, it's my guess that DDD isn't working with something else and Lycanites Mobs was what made it go over the edge.

**Comment by HaaDT** [comment] 2021-10-01 16:50
[crash-2021-10-01_12.47.37-server.txt](https://github.com/yeelp/Distinct-Damage-Descriptions/files/7268824/crash-2021-10-01_12.47.37-server.txt)
[crash-2021-10-01_12.47.42-client.txt](https://github.com/yeelp/Distinct-Damage-Descriptions/files/7268825/crash-2021-10-01_12.47.42-client.txt)

here sorry the delay was a little busy

**Comment by yeelp** [comment] 2021-10-01 18:46
Hmm... Neither report makes any mention of either Distinct Damage Descriptions or Lycanites Mobs. They don't mention... any mod really. All they say is what happened, which occurred vanilla's code only, and say that Distinct Damage Descriptions and Lycanites Mobs loaded successfully, along with every other mod. Not even VanillaFix points to Distinct Damage Descriptions as the source in these reports, so I can't even say for sure that DDD is even remotely responsible.

My guess would have to be Lycanites is trying to spawn something before it can safely, probably because some other mod somehow allowed it, it's some of the vanilla spawning code that crashes, but DDD doesn't touch mob spawning in any way.

Unfortunately, I can't say that DDD is the culprit here. I feel like you could recreate this crash regardless if DDD is present or not. (But do let me know if that isn't the case). For now, I'm going to have to close this because it doesn't seem to be caused by DDD at all.

**Closed by yeelp** 2021-10-01 18:46 UTC
Labels: bug

**Comment by HaaDT** [comment] 2021-10-01 19:52
I understand, I will keep testing, it must be some mod that is doing this, but thanks anyway, thank you and continue your mod it is very good
