### ISSUE TITLE
Crash On Server Side of SP

### ISSUE THREAD

**Issue by mmmilord** [yeelp/Distinct-Damage-Descriptions#18] opened 2020-09-20 23:07 UTC
https://gist.github.com/mmmilord/58d8f7772b79d2bba4e12b01ce60759d

**Comment by James103** [comment] 2020-09-22 03:37
Probably a duplicate of #6 and #14

**Comment by yeelp** [comment] 2020-09-23 14:48
Almost certainly a duplicate

**Comment by yeelp** [comment] 2020-09-23 16:51
commit 8e13ad07e21782c2fdcc41513776b85e354b01d2 should fix this.

**Closed by yeelp** 2020-09-23 16:51 UTC
Labels: bug, duplicate
