### ISSUE TITLE
[BUG] Symbols in Custom Config & No Version Number

### ISSUE THREAD

**Issue by Xarmat-GitHub** [yeelp/Distinct-Damage-Descriptions#36] opened 2021-01-11 15:23 UTC
In the Example Custom Config (both), there are a bunch of symbols at the end of the scrip.
Also there is no Version Number.

Screen Shoot:
[http://prntscr.com/wl34g0](http://prntscr.com/wl34g0)

Note:
Copy the text, don't copy the symbols.

**Comment by James103** [comment] 2021-01-11 15:24
Have you tried running a hexdump of the affected file(s)?

**Comment by Xarmat-GitHub** [comment] 2021-01-11 15:30
First, I don't know what "hexdump" actual means. But as far I understand it from google, I did not.

Steps:
- Deleted the old Configs from the last version
- Start MC once with the mod loaded

Extra:
- Symbols are there; In Visual Studio AND in Notpad++

**Comment by yeelp** [comment] 2021-01-11 16:11
Duplicate of #9 which I thought I fixed. I'm going to change the way I write the JSON files, if possible. Might avoid the problem if I write it line by line instead of byte by byte, although that may introduce other problems.

**Closed** 2021-02-17 21:15 UTC
Labels: bug, duplicate
