### ISSUE TITLE
[BUG][Crash] mob thaumcraft:taintacle

### ISSUE THREAD

**Issue by Xarmat-GitHub** [yeelp/Distinct-Damage-Descriptions#70] opened 2021-10-05 06:36 UTC
Bug Report: https://pastebin.com/dEFRFUFq
Note: I have some mods in my pack too. Maybe its one of them that can cause this. I have experienced something like this also with "Grimore of Gaia" mod. (will post them when it crashes again)

Reproduce:
- Modpack with DDD & Thaumcraft
- Start Game, create World
- Use this command while standing on surface: 
/summon thaumcraft:taintacle ~7 ~1 ~ {HandItems:[{Count:1,id:diamond_axe},{}], Attributes:[{Name:generic.attackDamage,Base:0}]} 

Important Note:
- mob thaumcraft:taintacle get damaged when not on tainted blocks
- Spawning the mob on tainted blocks, **cause no crash**

More Notes:
- The mob spawns underground and then grow upwards through the surface
- Maybe it gets "stuck in block" damage and "no tainted land" damage at the same time (then the mob itself can not be summoned with a command)
- I know that GoG (Grimore of Gaia) was also issues with this, but I never find out which mob causes this (and they spawn naturally)

If you can not reproduce this, then the bug will be on my side and I have to dig through my mods.

**Comment by yeelp** [comment] 2021-10-05 13:51
Before DDD crashes, it should have a chance to display debug info about the damage the taintacle took if debug mode is on. Not entirely sure it will help, but could you paste that info here too?

Regardless, the damage calculations is something I needed to look at anyway for the next update

**Comment by Xarmat-GitHub** [comment] 2021-10-05 14:00
Yeha, there are informations:
https://pastebin.com/rLZgLt75

**Comment by Xarmat-GitHub** [comment] 2021-10-05 14:13
Yeha, there are informations:
https://pastebin.com/rLZgLt75

So when I have to "guess" the bug, then I would say that spawning the entity "mid air" will not cause any damage at start.
When dropping to the ground, then it check the block it is on and start to tick "starve" damage like this:

[DDD (DEBUG)]Damage Type: **starve** Attacker: null, True Attacker: null Defender: thaumcraft:taintacle
[DDD (DEBUG)]starting damage: 1.0
[DDD (DEBUG)]Damage Total: {(ddd_normal (Special, built-in), 1.0)}
[DDD (DEBUG)]new damage after deductions: 1.0

But when spawning underground AND on a **none** taint block, then something breaks.
I only can not say why this should be. At the end there are two damage events: 
1. Spawn in block (block stuck damage) and
2. None tainted block nearby, so start taking damage each 20 ticks

**Comment by yeelp** [comment] 2021-10-05 14:23
I'm not entirely sure why there's a difference between the different scenarios. What I can say is that this is *very* likely a duplicate of #62, which is something I plan to tackle this update by redoing the calculation process. I'm delegating that issue to handle these types of crashes.

As a bit of a rule of thumb, when using version 1.3.x-beta, if the crash log starts with something like:
```
java.lang.NullPointerException
    at yeelp.distinctdamagedescriptions.handlers.DamageHandler.onHit(DamageHandler.java:112)
```

then it's likely a duplicate of #62.

That being said, it doesn't hurt to post a pastebin of any of those crash reports to #62 just in case.

**Closed by yeelp** 2021-10-05 14:23 UTC
Labels: bug, duplicate
